### ISSUE TITLE
Update SQL for bird-tracking-wmh

### ISSUE THREAD

**Issue by peterdesmet** [inbo/data-publication#52]
_Note: Data verified for [unpublished version](https://github.com/LifeWatchINBO/data-publication/blob/71d73a6b232c170558a24ecc89e967ae0d6bf568/datasets/bird-tracking-wmh-occurrences/mapping/dwc-occurrence-100.csv) on 2015-10-06. **Metadata** has been not yet been updated (waiting for gull data paper)._

Changes to apply:
- [x] Use DOI as `datasetID` (once issued)

Questions:
- [x] Is the `datasetName` OK?
- [x] What do we choose as `organismID`? Ideally it should be a code that is used internationally and across projects. For `gull` we chose `ring_code`. https://github.com/LifeWatchINBO/bird-tracking-wmh-occurrences/issues/6 Candidates:
  
  ``````
  ```
  device_info_serial: 586
  bird_name:          Mia
  color_ring_code:    -
  ring_code:          H173481
  ```
  ``````
- [x] Do all the fields in `bird_tracking_devices` make sense in the context of wmh?
- [ ] Do outlier criteria make sense for wmh?

**Comment by peterdesmet** [comment]
Outliers will be addressed in data paper. Ring code seems most logical one (cf. gulls). Name and device_info_serial available in other fields.
