### ISSUE TITLE
Update saltabel SQL

### ISSUE THREAD

**Issue by peterdesmet** [inbo/data-publication#57]
_Note: Data verified for version 5.2 on 2015-10-07. **Metadata** is still under review (waiting for data paper incorporation), see #61._

Changes to apply:
- [x] Use lowerCamelCase field names
- [x] For `type`, use UpperCamelCase `Event` and `PhysicalObject`.
- [x] Use `occurrenceID` instead of `GUID`
- [x] Remove `modified`: it contains values such as `1800`, `1982-08-28/1982-09-11` and `Unknown`: https://github.com/LifeWatchINBO/saltabel-occurrences/issues/11
- [x] Rename `rights` to `license`
- [x] Update `accessRights`
- [x] Only populate `catalogNumber` for `PreservedSpecimen` (currently populated for all) → We don't have those
- [x] Leave `collectionCode` blank for `HumanObservations`: currently `FSAG` for 273 records
- [x] Always populate `collectionCode` for `PreservedSpecimen`: currently blank for 1270 records → Collection is not known
- [ ] Use the actual code for `collectionCode`, not the full name
- [x] Use dataset DOI in `datasetID`
- [x] For `basisOfRecord`, use UpperCamelCase: `PreservedSpecimen`, `HumanObservation`
- [x] Verify delimiter in `recordedBy`
- [x] Remove `-` from `-M Bodart` in `recordedBy` → Will fix in source DB
- [x] Verify `individualCount`:  two big values (`15000`) but all numbers. → Verified with Tim
- [x] Use JSON for `sex` (currently `female: 1 | male: 9`) → Will not include counts
- [x] Use JSON for `lifeStage` (currently `juvenile: 111`) or even better, a simple value: `juvenile` → Will not include counts 
- [x] Remove `verbatimEventDate`: it is the same as `eventDate` → Keep for ranges only
- [x] Remove the 3 `unknown` values from `eventDate` (= leave blank): https://github.com/LifeWatchINBO/saltabel-occurrences/issues/4
- [x] Add `samplingProtocol` → Not much more known than `type`
- [x] Add a `samplingEffort` → Not known.
- [x] Add `stateProvince` if feasible
- [x] Add `verbatimLatitude`, `verbatimLongitude`, `verbatimCoordinateSystem` and `verbatimSRS`
- [x] Verify delimiter in `identifiedBy`: only single names
- [x] Verify `class`: is it populated?
- [x] Verify `order`: is it populated?
- [x] Verify `taxonRank`: all species? Yes, all species .
- [ ] Remove unmapped columns
- [ ] Apply changes in production

Verify specimens vs observations:
- [x] `type` and `basisOfRecord` are linked: only `PhysicalObject` has `PreservedSpecimen`, the rest are `HumanObservation`s

Questions:
- [x] Shouldn't we move `dataGeneralizations` to `georeferenceRemarks`? It currently mentions `CoordinateUncertaintyInMeters depends on original UTM1 or UTM5 squares.`, but that is just a calculation: https://github.com/LifeWatchINBO/saltabel-occurrences/issues/8
- [x] Full names and abbreviated names are used in `recordedBy`:  should we standardize? The delimiter is OK. Idem for `identifiedBy`
- [x] What `collectionCode` should we use? `ORTH BEL RBINS` is listed in metadata for `RBINS` in dat we have `KBIN` and lots of other non really standardized names.
- [x] Should we add `collectionID`. For `RBINS` we could use `urn:lsid:biocol.org:col:35271` → No, too many with unknown code

**Comment by peterdesmet** [comment]
* [ ] `collectionCode`: somewhere in the data there is a code for the collection, rather than the full name. We should use that.
* [ ] `stateProvince`: should be available in the source data.
* [ ] `verbatimCoordinates`:
    * 3536: use UTM5 code, system: `UTM 5km`, SRS: `ED50`
    * 707: use UTM1 code, system: `UTM 1km`, SRS: `ED50`
    * 30: use actual XY coordinates, system: `Belgian Lambert 72`, SRS: `Belgium Datum 1972`
* [ ] `vernacularName`: is this available?
* [ ] `verbatimEventDate`: populate for ranges only
* [ ] `sex`: `male | female`
* [ ] `lifeStage`: `adult | juvenile`
* [ ] `behavior`: `stridulating`
* [ ] `occurrenceRemarks`: all categories
* [ ] `organismQuantity` or `individualCount`?

**Comment by stijnvanhoey** [comment]
Current `individualCount` on inbo IPT is sometimes Nan (empty).

I've checked these records in the recorder dbase, and these are linked with:
- "w.be" -> I assume some reference to waarnemingen.be, but no information about the count
- Vleugel, Vleugel;None or None -> also no count information given

=> @peterdesmet and TimAdriaens: How should we treat these records? Can we assume there is at least 1?

**Comment by timadriaens** [comment]
indeed, to be treated as an occurrence, so at least 1

**Comment by stijnvanhoey** [comment]
@peterdesmet  with respect to `organismQuantity`:
- we used scarce, numerous and very numerous - > ok?
- it requires also the addition of an `organismQuantityType`,  but the Dwc information is not really clear, I propose empty string when no info in organismQuantity and `abundance` when info is available?

**Comment by peterdesmet** [comment]
@timadriaens, what terms do you prefer?

    scarce
    numerous
    abundant / very numerous?

@stijnvanhoey, yep the `organismQuantityType = abundance` seems good for those records where we populate `organismQuantity`.

**Comment by timadriaens** [comment]
I'd stick to the Tansley (DAFOR) scale as closely as possible so would change to

rare = a small number of individuals
frequent = found at several places, usually more than just a few individuals
abundant = very common in many parts of the location

**Comment by peterdesmet** [comment]
So what would be a good name for the `type` then? `DAFOR scale` ?

**Comment by timadriaens** [comment]
no, it's an own invention. DAFOR is in fact for plants (and it's nice because it a combination of abundance and some spatial idea on that too). So just call it abundance.

**Comment by stijnvanhoey** [comment]
With regards to the following remaining issues, I would like to mention:
* [ ] `stateProvince`: since we are using the UTM 5 and/or 1 for many of the records,deriving the province based on a spatial query of the coordinates (centers of the centroid), we actullay mlink some of them with the wrong province (when centroid is in the province, but actual measurement would be in neighbouring province). I only added the province in the records with specific XY-coordinates 
* [ ] `verbatimCoordinates`: The difference between XY and UTM5/1 has been made in the verbatimcoordinates as mentioned in comment of Peter; what is left to do:
    * currently SRS: `ED50` is used when UTM5/1, but I should check with Jo if valid
    * The specific grid code need to be added
* [ ] `vernacularName`: is this available? Still to check where...
* [ ] `verbatimEventDate`: populate for ranges only -> to check with Jo (change function)

**Comment by timadriaens** [comment]
@stijnvanhoey province was manually filled in the database (specifically because of the problem you mention and the fact that we sometimes needed to analyse data per province)

vernacular names: I have attached a list

[saltabel_species.xlsx](https://github.com/LifeWatchINBO/data-publication/files/146259/saltabel_species.xlsx)

I also attach the document of how data were put in recorder (<Frederik)
[Dataset Saltabel.docx](https://github.com/LifeWatchINBO/data-publication/files/146262/Dataset.Saltabel.docx)

This mentions references for some of the literature records. I guess these should go in the data paper?

**Comment by stijnvanhoey** [comment]
@timadriaens, this manually filling in: was this with english or dutch names and what styling conventions (capital letters, hyphens?) ?

I fond vernacular names in one of the lists, quick screening learns me that it should be corresponding to your attached list. 

References is indeed for the datapaper...

**Comment by stijnvanhoey** [comment]
Provinces were not imported in the NDNdbase, so we can not directly reconstruct this within the query for the grid-based references. I propose to stick to the ones available in the dbase.

**Comment by peterdesmet** [comment]
@stijnvanhoey convention on names is to use those as available in the nameserver, in Dutch. For English names we generally try to use lowercase names, for birds, capitalized names seem to be the convention.

**Comment by stijnvanhoey** [comment]
Small subselection from the naming of vernacularnames:
```
Greppelsprinkhaan
Grote groene sabelsprinkhaan
Zanddoorntje
Kustsprinkhaan
Ratelaar
Struiksprinkhaan
Boomsprinkhaan
Gewoon spitskopje
Grote groene sabelsprinkhaan
Heidesabelsprinkhaan
Huiskrekel
Zeggedoorntje
Gewoon doorntje
Moerassprinkhaan
Negertje
Bruine sprinkhaan
Ratelaar
Snortikker
Kustsprinkhaan
Krasser
Knopsprietje
Boomsprinkhaan
Gewoon spitskopje
Grote groene sabelsprinkhaan
Heidesabelsprinkhaan
Gewoon doorntje
Moerassprinkhaan
Negertje
Bruine sprinkhaan
Ratelaar
Snortikker
Kustsprinkhaan
Krasser
Knopsprietje
Sikkelsprinkhaan
Ratelaar
Snortikker
Bruine sprinkhaan
Boskrekel
Krasser
Sikkelsprinkhaan
Blauwvleugelsprinkhaan
Ratelaar
Snortikker
Bruine sprinkhaan
Sikkelsprinkhaan
Heidesabelsprinkhaan
Boskrekel
Negertje
Krasser
Zadelsprinkhaan
Veldkrekel
Veenmol
```

**Comment by stijnvanhoey** [comment]
I would call it ok for the moment:
* `verbatimCoordinates`: 
    * currently SRS: `ED50` is used when UTM5/1 (question is still pending with GIS group)
    * The specific grid code need is added: for the UTM1 however only flanders-codes; in the dbase there is no UTM1 for Wallonia, so these are left blank; for UTM5 all gridcodes are available.
* Provinces only added when explicit XY-coordinates are present.

**Comment by peterdesmet** [comment]
@timadriaens, I have validated the whole data file (with a new proof of concept, which will automate validation in the future :metal:) and have the following questions:

* [ ] Can records defined as derived from `Text` (= "reference") be considered HumanObservations, or could those be specimens as well?
* [ ] Is INBO considered `rightsHolder` for ALL records?
* [ ] Did we decide to use a code or full name for `collectionCode`? Currently we use a full name (e.g. `Inst. V. Beneden`), probably because it is more recognizable.
* [ ] Is it normal that 3 records have no date?
* [ ] For records in Wallonnia, we're not adding the UTM grid code, because we don't have a reference GRID layer. Should we look for this?

Todo for @stijnvanhoey:

* [x] Add `adult` if sex is populated
* [ ] Verify with GIS team that UTM squares indeed ED50
* [ ] Add georeferenceRemarks (see validation)

Todo for @peterdesmet:

* [ ] Depending on answer to the last question for Tim, allow `verbatimCoordinateSystem`, `verbatimSRS` and `coordinateUncertaintyInMeters` and `georeferenceRemarks` in the validation.

**Comment by DimEvil** [comment]
What we are not doing, is adding our own (or even @timadriaens ) his interpretation in the database. We published the data in Saltabel. Updating the database is another job.. (we might do if we agree on this).
If the count is not given in the database, the count is not given. And we will not put '1' instead. It is information missing in the database.
We should drop all the UTM issues, as in NBN we only have the original coordinate. The UTM squares were not imported.

**Comment by DimEvil** [comment]
@peterdesmet   can you already do a whip to see what comes out :)

**Comment by timadriaens** [comment]
A few answers to the above questions @peterdesmet @DimEvil 

- records derived from text can be considered human observations
- INBO can be considered right holder for the Saltabel records indeed

I don't know if we still need to get into this, but having been the database manager for many years and spending lots of time looking up locations and filling the right utm square, I find it a pitty that utm was not imported in NBN. This should be easy to fix considering all records have unique ids. Walloon records also had utms no?

**Comment by DimEvil** [comment]
Well, we might need to do this import  again... as for as much as I could see, the original ID's were not imported in NBN. I need to check this with Frederic. I remember I always stressed on the fact that we should keep the original ID's, so I don't know why they are not there. (it was 2013)

[D0017_00_NBNData].[inbo].[Saltabal5juli2013Bewerkt]) is the file I could find.. It has all the observations, inclusive id's and UTM and coordinates.

We could do a spatial join betweet UTM squares and the verbatim coördinates to add the squares, but that also would be a calculation.

Let's see how we can take this further with Frederic.

**Comment by DimEvil** [comment]
all right, after digging deep enough I was able to find the UTM squares, they will be there in the next update @timadriaens

**Comment by DimEvil** [comment]
Also added the verbatim latitude and longitude (Lambert)

**Comment by peterdesmet** [comment]
- [ ] basisOfRecord: use `HumanObservation`, `PreservedSpecimen`
- [ ] behavior: we used to have `stridulating` for some occ. I notice there is now `Zangpost` in `lifeStage`. This information should be mapped as `stridulating` in `behavior`, optionally setting `lifeStage` to `adult`
- [ ] catalogNumber: remove term: this is just the last part of the occurrenceID and we don't have this for other datasets
- [ ] dataGeneralizations: "Coordinate Uncertainty In Meters depends on original UTM1 or UTM5 squares." Remove term, this is georeference information
- [ ] eventDate: `Unknown`: just use empty values
- [ ] lifeStage: why `adult | juvenile` and `juvenile | adult`?
- [ ] sex: why `male | female` and `female | male`?
- [ ] occurrenceRemarks: we used to have `{"female": 4, "male": 1}` are we no longer doing this?
- [ ] verbatimCoordinateSystem: add term, with values `UTM 1km`, `UTM 5km`, and something for coordinates
- [ ] organismQuantity: we used to have `abundant`, `numerous`, `scarce` with organismQuantityType `abundance`
- [ ] type: use uppercamelcase: Event, PhysicalObject, Sound, StillImage, Text

**Comment by peterdesmet** [comment]
@DimEvil I'm expecting the coordinates to be like this:

verbatimCoordinateSystem | verbatimSRS | verbatimCoordinates | verbatimLat | verbatimLong | coordinateUncertaintyInMeters | georeferenceRemarks
--- | --- | --- | --- | --- | --- | ---
Lambert coordinates | Belgian Datum 1972 | (empty) | 000000 | 000000 | 30 | (empty)
UTM 1km | ED50?? | AA0000 | (empty) | (empty) | 707 | coordinates are centroid of used grid square
UTM 5km | ED50??  | AA00A | (empty) | (empty) | 3565 | coordinates are centroid of used grid square

**Comment by DimEvil** [comment]
@peterdesmet Data is ready for the whip

**Comment by peterdesmet** [comment]
- [ ] 273 records have collectionCode `FASG`, but are not preserved specimens (they are HumanObservation > Event)
- [ ] organismQuantity & organismQuantityType not included
- [ ] move behavior column right after lifeStage
- [ ] occurrenceRemarks not included
- [ ] 3 records have no date
- [ ] Put content of verbatimEventDate in eventDate and remove verbatimEventDate, GBIF accepts ranges

**Comment by peterdesmet** [comment]
Almost there:

- coordinateUncertaintyInMeters: 70 -> 71
- verbatimLat/Long: round numbers (no comma)
- verbatimSRS: still contains rogue coordinates
- The 273 FASG have PhysicalObject, but not PreservedSpecimen. I think that can be assumed.

**Comment by DimEvil** [comment]
ready for whip @peterdesmet

**Comment by peterdesmet** [comment]
All issues have been resolved. 👏  I only noticed that simply applying 31U to the UTM codes is incorrect, but I made an SQL update on how to correct that: #173 @DimEvil can you see if that runs on the server?

**Comment by peterdesmet** [comment]
"Hooray, your data set is according to the guidelines!"
